name: Publish to NPM
on:
  release:
    types: [published]
  push:
    branches:
      - tp/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Parse version from tag
        id: version
        uses: release-kit/semver@v2
        with:
          fallback: 'v7.1.0-alpha+1'

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn install
      - run: yarn test

      - uses: JS-DevTools/npm-publish@v3
        if: "!github.event.release.prerelease"  
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          dry_run: true

      - name: Upload npm debug log
        if: failure()  # This step will run only if the previous steps failed
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-logs
          path: /home/runner/.npm/_logs/*.log
